/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CariRouteImport } from './routes/cari'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MitraSlugRouteImport } from './routes/mitra.$slug'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as KategoriCategoryRouteImport } from './routes/kategori.$category'
import { Route as AuthenticatedDonorRouteImport } from './routes/_authenticated/donor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const CariRoute = CariRouteImport.update({
  id: '/cari',
  path: '/cari',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MitraSlugRoute = MitraSlugRouteImport.update({
  id: '/mitra/$slug',
  path: '/mitra/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriCategoryRoute = KategoriCategoryRouteImport.update({
  id: '/kategori/$category',
  path: '/kategori/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDonorRoute = AuthenticatedDonorRouteImport.update({
  id: '/donor',
  path: '/donor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cari': typeof CariRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donor': typeof AuthenticatedDonorRoute
  '/kategori/$category': typeof KategoriCategoryRoute
  '/listing/$id': typeof ListingIdRoute
  '/mitra/$slug': typeof MitraSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cari': typeof CariRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donor': typeof AuthenticatedDonorRoute
  '/kategori/$category': typeof KategoriCategoryRoute
  '/listing/$id': typeof ListingIdRoute
  '/mitra/$slug': typeof MitraSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cari': typeof CariRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/donor': typeof AuthenticatedDonorRoute
  '/kategori/$category': typeof KategoriCategoryRoute
  '/listing/$id': typeof ListingIdRoute
  '/mitra/$slug': typeof MitraSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cari'
    | '/admin'
    | '/dashboard'
    | '/donor'
    | '/kategori/$category'
    | '/listing/$id'
    | '/mitra/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cari'
    | '/admin'
    | '/dashboard'
    | '/donor'
    | '/kategori/$category'
    | '/listing/$id'
    | '/mitra/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cari'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/donor'
    | '/kategori/$category'
    | '/listing/$id'
    | '/mitra/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CariRoute: typeof CariRoute
  KategoriCategoryRoute: typeof KategoriCategoryRoute
  ListingIdRoute: typeof ListingIdRoute
  MitraSlugRoute: typeof MitraSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cari': {
      id: '/cari'
      path: '/cari'
      fullPath: '/cari'
      preLoaderRoute: typeof CariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitra/$slug': {
      id: '/mitra/$slug'
      path: '/mitra/$slug'
      fullPath: '/mitra/$slug'
      preLoaderRoute: typeof MitraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$category': {
      id: '/kategori/$category'
      path: '/kategori/$category'
      fullPath: '/kategori/$category'
      preLoaderRoute: typeof KategoriCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/donor': {
      id: '/_authenticated/donor'
      path: '/donor'
      fullPath: '/donor'
      preLoaderRoute: typeof AuthenticatedDonorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDonorRoute: typeof AuthenticatedDonorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDonorRoute: AuthenticatedDonorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CariRoute: CariRoute,
  KategoriCategoryRoute: KategoriCategoryRoute,
  ListingIdRoute: ListingIdRoute,
  MitraSlugRoute: MitraSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
